language: android
jdk: oraclejdk8
env:
  global:
  - secure: "ThK698oQ7R33PKA3uqBuddTen/90cevoeVpw6aSDYQNtdK43ztUlII7jlIork/6OFTsl5EbodtLUGU5YyCQ49n+6lzGgd7A+NQKb6Buet33GL9xcZHWzXJNHTu0nsNaG+Ojp7D+MyXNHjFxVWv0S+hSnPYh2bjSclDZa1KxMRWk1LEo/bzyG0pl46ow1x3VzzukRZI3bFd24FnDWarRmY9tgZZFtOWloYDWSQSmfJg9b/a2Lhvvks31l03gihCg2eLqcWvbB/G2hDEi6PaOVVoedywNjjFRlhMlVc12psT5HDN5G+DtrwvI6BpTTuIjsm4nhpZxpRuUuz9cVnDX4lQmspBXKhIMkzGUwK/b2+ZJKzfYQ6rvMLKFNZDxsLXRuMxTvh1iOanZGnXhb4N2qSAYQLPTgtDxQxKWQAi9wDrvKXT0i8y0Z4TxNllZ2sNhk6fRAd0TJj0158NEMk097XuH6MGnJT48b9n8m/QwuXWqBKwBM0IWVBRKebyOXno5qZi/S4aNzig60aueA/O80dJi6BdJjJ8+BcHHSaHt5nlUOhR4VjLoUxNOC718kqmp9aEWmMgLeLaUXUCe410IzV2kyR7uFGbOZkgCjzg+9X06CyUH52BiDcbpswOGsPquIAS3qfJUH1UBouxNn8MlMJG7hLoymNoN7w8aWuM3dMkY="
  - secure: "BIZfVxxPYoEhbSDDOCn3NByw87+K1SxAfhHd15T7FqT/zncIGT9od+IFHfdgksgca5Ykp7FA/QC24mKpL3dCezAv+KP/0MzB3cC2VgjKtzTnaZVk3fTyqt6vov4t5XONQwqY1K1d70YzIlmh7kUJsmNqvm6zPNN6bm4etNrWC8ti4d05AgN/OFGFYI2U1H+siR0KaTVcNOvmaxsIiM/vTXDxpJoLmhAJzwONH3a3g5bHMr7kWYHR6m7wk7SG4XmXlNsj4LyATj2Sg9JYwiGHkMPu4dhRaSLAElir5IW8JYapNyCl0TQgKNRHG/4FaMg/m3XPCIDYczsxQQtvhEwGJi540pcqrrAXHk0O9oyivL1UdSIqfWs8xPfEJTomPjyZT9I6dLi/z6AEiALN6oAH3AGBgl9EGVWX0KYkHhVDyScy6C/xY9NDGPcgMoRwgK0IH3g4vKN1t2Ar4X6ma7kI7+ARLiIyP3CEJ2WmajJLMdUYiWpLP1R9cJgV1BYDvpRklL//w05kgiEG7+TZK0olkTPUPItdq4v03DGT54s+ixAa0HMDSnrNoUt4CIm70XxSE+PPPGZOPkbHZparYSNSVKKjjGFqlu1hsSQ3SrG6TO1KnaHucAhcR3dvu0OZa9QrltkLq+GMk90utjIhbNUY4sMScSWa12LgfMDpKsugzec="
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
  - addon-google_apis-google-27
  licenses:
  - android-sdk-preview-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
- "./gradlew build check"
- "./gradlew test"
deploy:
  provider: releases
  api_key: "$GITHUB_KEY"
  file_glob: true
  file: app/build/outputs/apk/release/PinItAndroid.apk
  overwrite: true
  skip_cleanup: true
  on:
    repo: Pin-It/PinItMobileApp
    branch: master
    tags: true
before_install:
- openssl enc -aes-256-cbc -d -in keystore.jks.enc -out keystore.jks -base64 -K $TRAVIS_KEY
  -iv $TRAVIS_IV
